spring.application.name=Authentication
server.address=0.0.0.0

#Postgres config
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=123456

#Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT config
jwt.secret=mySuperSecretKeyForJwtAuthentication12345
jwt.expiration=3600000